# Generated by Django 3.2 on 2021-04-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='kek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choicer', models.IntegerField(choices=[(1, 'lol'), (2, 'kek'), (3, 'uzbek')])),
            ],
        ),
    ]
