# Generated by Django 3.1.7 on 2021-04-28 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readystatus',
            old_name='ready',
            new_name='application',
        ),
    ]
