# Generated by Django 3.2 on 2021-04-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_kek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kek',
            name='choicer',
            field=models.CharField(choices=[('1', 'lol'), ('2', 'kek'), ('3', 'uzbek')], max_length=2),
        ),
    ]
