# Generated by Django 3.2 on 2021-04-12 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_kek_choicer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkstatus',
            name='status',
            field=models.CharField(choices=[('accepted', 'Заявка принята'), ('rejected', 'Заявка отклонена'), ('revision', 'Заявка отправлена на доработку')], max_length=8),
        ),
    ]
