# Generated by Django 3.2 on 2021-04-12 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_checkstatus_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='kek',
        ),
        migrations.AlterField(
            model_name='checkstatus',
            name='status',
            field=models.IntegerField(choices=[(0, 'Заявка принята'), (1, 'Заявка отклонена'), (2, 'Заявка отправлена на доработку')], max_length=8),
        ),
    ]
