# Generated by Django 3.2 on 2021-04-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20210412_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkstatus',
            name='status',
            field=models.CharField(choices=[('accepted', 'Заявка принята'), ('rejected', 'Заявка отклонена'), ('revision', 'Заявка отправлена на доработку')], max_length=8),
        ),
    ]
